### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by zakirkun** [irvanherz/pos#1]
Apakah Database Otomatis Kegenerate ke mysql?

**Comment by irvanherz** [comment]
> Apakah Database Otomatis Kegenerate ke mysql?

Tidak mas. Ada databasenya sendiri. Dan kebetulan belum saya ikutkan di repo

**Comment by zakirkun** [comment]
apakah boleh mas databasenya di naikan sekalian?

**Comment by irvanherz** [comment]
> apakah boleh mas databasenya di naikan sekalian?

Iya, boleh. Nanti atau besok kebetulan saya mau commit yang error

**Comment by zakirkun** [comment]
makasih mas
